import json
from typing import Optional

from groq import Groq, APIStatusError, APITimeoutError

import config

_client = Groq(api_key=config.GROQ_API_KEY)

_SYSTEM_PROMPT = """You are an AI content attribution classifier. Your task is to assess whether a piece of text was written by a human or generated by an AI.

Analyze the text for:
- Tonal consistency and register (AI tends to be uniformly formal or uniformly casual)
- Sentence flow and variety (AI tends to be smooth and predictable)
- Presence of filler phrases common in AI output (e.g., "it is important to note", "furthermore", "in conclusion", "it is worth mentioning")
- Personal voice, quirks, or unexpected phrasing (more common in human writing)
- Grammatical perfection vs. natural imperfection

Respond with ONLY a JSON object in this exact format, no additional text:
{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}

Where ai_probability is:
- Close to 1.0 if you are confident the text is AI-generated
- Close to 0.0 if you are confident the text is human-written
- Around 0.5 if you are uncertain"""


def classify_text(text: str) -> Optional[float]:
    """
    Returns a float 0–1 representing the probability the text is AI-generated.
    Returns None if the API call fails or the response cannot be parsed.
    """
    if not text or not text.strip():
        return None

    try:
        response = _client.chat.completions.create(
            model=config.GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Classify this text:\n\n{text}"},
            ],
            temperature=0.1,
            max_tokens=150,
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if the model wraps the JSON
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])

        if not 0.0 <= score <= 1.0:
            return None

        return score

    except (APIStatusError, APITimeoutError):
        return None
    except (json.JSONDecodeError, KeyError, ValueError, TypeError):
        return None
